version: "3.7"

services:
  studio-mongo:
    container_name: studio-mongo
    image: mongo:latest
    volumes:
      - ./storages/mongo-database/:/data/db
    networks:
      - internal

  studio-api:
    container_name: studio-api
    image: linto-studio/studio-api
    build:
      context: ./studio-api
      dockerfile: Dockerfile
    env_file: ./studio-api/.dockerenv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./storages/studio-api/:/usr/src/app/conversation-manager/storages/
    command:
      - --run-cmd=node app.js
    ports:
      - "8001:80"
    networks:
      - internal

  studio-websocket:
    container_name: studio-websocket
    image: linto-studio/studio-websocket
    build:
      context: ./studio-websocket
      dockerfile: Dockerfile
    env_file: ./studio-websocket/.dockerenv
    ports:
      - "8002:80"
    networks:
      - internal

  studio-frontend:
    container_name: studio-frontend
    image: linto-studio/studio-frontend
    build:
      context: ./studio-frontend
      dockerfile: Dockerfile
    env_file: ./studio-frontend/.dockerenv
    command:
      - --build
    ports:
      - "8003:80"
    networks:
      - internal

  studio-dashboard:
    container_name: studio-dashboard
    image: linto-studio/studio-dashboard
    build:
      context: ./studio-dashboard
      dockerfile: Dockerfile
    env_file: ./studio-dashboard/.dockerenv
    ports:
      - "8004:80"
    networks:
      - internal

networks:
  internal:
