version: '3.7'

services:
  conversation-manager-api:
    build: .
    image: lintoai/linto-platform-conversation-manager
    container_name: conversation-manager
    env_file: .env
    environment: 
      - WEBSERVER_HTTP_PORT=80 #Match the expose Dockerfile, but docker-compose will use the WEBSERVER_HTTP_PORT .env settings
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./${VOLUME_AUDIO_UPLOAD_PATH}:/usr/src/app/conversation-manager/${VOLUME_AUDIO_UPLOAD_PATH}
    command:
      - --rebuild-vue-app
      - --run-cmd=node app.js
    ports:
      - "${WEBSERVER_HTTP_PORT}:80"
    networks:
      - linto-net

  conversation-manager-mongo:
    container_name: conversation-manager-mongo
    image: mongo:latest
    env_file: .env
    volumes:
      - ${VOLUME_DATABASE_FOLDER}/:/data/db
      - ./mongo-seeds/init.js:/docker-entrypoint-initdb.d/init.js
    ports:
      - 27017:27017
    expose:
      - "27017"
    networks:
      - linto-net

networks:
  linto-net:
    external: true