# Only send what's needed to the Docker daemon
*
!studio-frontend/
!studio-sdk/components/editor/
studio-frontend/node_modules/
studio-frontend/dist/
studio-frontend/.env
studio-frontend/.env.*
studio-frontend/.git/
studio-sdk/components/editor/node_modules/
