// ── Atoms ──────────────────────────────────────────────────────────────
export { default as Badge } from './atoms/Badge.vue'
export { default as Button } from './atoms/Button.vue'
export { default as CodeBlock } from './atoms/CodeBlock.vue'
export { default as CopyButton } from './atoms/CopyButton.vue'
export { default as EditableText } from './atoms/EditableText.vue'
export { default as EditorCheckbox } from './atoms/EditorCheckbox.vue'
export { default as EditorIcon } from './atoms/EditorIcon.vue'
export { default as MarkdownEditor } from './atoms/MarkdownEditor.vue'
export { default as MarkdownView } from './atoms/MarkdownView.vue'
export { default as PopoverList } from './atoms/PopoverList.vue'
export { default as SelectableListItem } from './atoms/SelectableListItem.vue'
export { default as SpeakerIndicator } from './atoms/SpeakerIndicator.vue'
export { default as SwitchToggle } from './atoms/SwitchToggle.vue'
export { default as UserAvatar } from './atoms/UserAvatar.vue'
export { resolveIcon, iconMap, ICON_SIZES } from './atoms/icons'

// ── Molecules ──────────────────────────────────────────────────────────
export { default as DocumentArticle } from './molecules/DocumentArticle.vue'
export type { DocumentArticleStatus } from './molecules/DocumentArticle.vue'
export { default as DownloadMenu } from './molecules/DownloadMenu.vue'
export type { DownloadFormat } from './molecules/DownloadMenu.vue'
export { default as FormInput, EMPTY_FIELD } from './molecules/FormInput.vue'
export type { FormField } from './molecules/FormInput.vue'
export { default as SpeakerMenu } from './molecules/SpeakerMenu.vue'
export { default as Tabs } from './molecules/Tabs.vue'
export type { TabItem } from './molecules/Tabs.vue'
export { default as TurnTextEditor } from './molecules/TurnTextEditor.vue'

// ── Utils ──────────────────────────────────────────────────────────────
export { renderMarkdown, renderMarkdownSegments } from './utils/markdown'
export { computeInitials } from './utils/computeInitials'
export { placeCaretAt } from './utils/placeCaretAt'
export { computeSelectionOffset } from './utils/computeSelectionOffset'
export { computeTextOffsetInContainer } from './utils/computeTextOffsetInContainer'
export { getShadowAwareSelection, getSelectionFocus } from './utils/shadowAwareSelection'
