import test from "ava"
import mergeSession from "../mergeSession.js"

test("deep merge two session", (t) => {
  const oldSession = {
    id: "f4d59885-2c93-4a57-90c4-e977f163e87a",
    status: "ready",
    name: "multi langue microsoft",
    startTime: "2025-01-14T12:59:17.140Z",
    endTime: null,
    scheduleOn: null,
    endOn: null,
    erroredOn: null,
    owner: "655f76185ebf391b4def21d0",
    organizationId: "6785238f0aee1be21684a9e1",
    visibility: "organization",
    autoStart: true,
    autoEnd: false,
    meta: null,
    createdAt: "2025-01-14T12:57:57.641Z",
    updatedAt: "2025-01-14T14:17:30.322Z",
    channels: [
      {
        id: 137,
        keepAudio: true,
        diarization: false,
        languages: ["en-GB"],
        translations: ["it", "ja"],
        name: "DG SCIC Custom Model EN",
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,1&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/1",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,1",
        },
        streamStatus: "inactive",
        transcriberId: null,
        closedCaptions: null,
        audioFile: "",
        bot: false,
        createdAt: "2025-01-14T12:57:57.649Z",
        updatedAt: "2025-01-14T12:57:57.656Z",
        transcriberProfileId: 2,
        index: 0,
      },
      {
        id: 136,
        keepAudio: true,
        diarization: false,
        languages: ["fr-FR"],
        translations: ["en", "ar"],
        name: "DG SCIC Custom Model FR",
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,0&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/0",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,0",
        },
        streamStatus: "inactive",
        transcriberId: null,
        closedCaptions: [
          {
            end: 30.07,
            lang: "fr-FR",
            text: "Comment peut-on atteindre ses fins ? Le mot fin FIN en français a 2 sens que tout paraît séparé mais qu'il faut peut être relier, rejoindre et où il y a aussi une forme de risque qu'il faut arriver à dépasser. Le terme fin, FIN toujours désigne en effet en français non seulement le terme atteint par une réalité dans son développement, par exemple à la fin de notre vie.",
            start: 4.39,
            astart: "2025-01-14T12:59:17.121Z",
            translations: {
              ar: "كيف يمكننا تحقيق غاياتنا؟ كلمة نهاية نهاية في الفرنسية لها معاني أن كل شيء يبدو منفصلا ولكن ربما يجب علينا الاتصال والانضمام وحيث يوجد أيضا شكل من أشكال المخاطر التي يجب أن نتمكن من التغلب عليها. يشير مصطلح النهاية ، FIN toujours ، بالفرنسية ليس فقط المصطلح الذي يصل إليه واقع في تطوره ، مثلا في نهاية حياتنا.",
              en: "How can we achieve our ends? The word end END in French has 2 meanings that everything seems separate but that we must perhaps connect, join and where there is also a form of risk that we must manage to overcome. The term end, FIN toujours, designates in French not only the term reached by a reality in its development, for example at the end of our life.",
            },
          },
          {
            end: 56.11,
            lang: "fr-FR",
            text: "La fin de vie qui est bornée en quelque sorte par l'expérience de la mort, mais il désigne aussi le terme ou le but fixé à une action dans la représentation humaine de l'action. Pour nous, esprit humain, l'action consiste en effet à se représenter un but que nous visons, un terme où l'action serait dite, achevée, accomplie. Il y a donc bien un lien entre les 2 sens du mot, mais dont nous sommes séparés par.",
            start: 30.39,
            astart: "2025-01-14T12:59:17.121Z",
            translations: {
              ar: "نهاية الحياة التي تقتصر بطريقة ما على تجربة الموت ، ولكنها تحدد أيضا المصطلح أو الهدف المحدد للفعل في التمثيل البشري للفعل. بالنسبة لنا، الروح البشرية، يتمثل الفعل في تمثيل هدف نسعى إليه لأنفسنا، مصطلح يقال فيه الفعل ويكتمل ويحقق. لذلك هناك رابط بين 2 من المعاني للكلمة ، ولكن نحن منفصلون عنهما.",
              en: "The end of life which is limited in a way by the experience of death, but it also designates the term or goal set for an action in the human representation of action. For us, the human spirit, action consists in representing to ourselves a goal that we aim at, a term at which the action would be said, completed, accomplished. So there is a link between the 2 meanings of the word, but from which we are separated by.",
            },
          },
        ],
        audioFile: "",
        bot: false,
        createdAt: "2025-01-14T12:57:57.644Z",
        updatedAt: "2025-01-14T14:17:30.313Z",
        transcriberProfileId: 1,
        index: 1,
      },
    ],
  }

  const newSession = {
    id: "f4d59885-2c93-4a57-90c4-e977f163e87a",
    status: "active",
    scheduleOn: null,
    endOn: null,
    autoStart: true,
    autoEnd: false,
    channels: [
      {
        id: 136,
        translations: ["en", "ar"],
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,0&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/0",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,0",
        },
        streamStatus: "active",
        diarization: false,
        keepAudio: true,
        transcriberProfile: {
          config: {
            type: "microsoft",
            name: "DG SCIC Custom Model FR",
            description: "DG SCIC Custom Model FR",
            languages: [
              {
                candidate: "fr-FR",
                endpoint: "f8a073cb-27ea-45c4-80fb-c44a55297c95",
              },
            ],
            region: "westeurope",
            key: "4612cd17f7774661a481205178bb686a",
            availableTranslations: [
              "ar",
              "eu",
              "bs",
              "bg",
              "zh",
              "zhh",
              "cs",
              "da",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "gl",
              "de",
              "el",
              "hi",
              "hu",
              "id",
              "it",
              "ja",
              "ko",
              "lv",
              "lt",
              "mk",
              "nb",
              "pl",
              "pt",
              "ro",
              "ru",
              "sr",
              "sk",
              "sl",
              "es",
              "sv",
              "th",
              "tr",
              "uk",
              "vi",
              "cy",
            ],
            hasDiarization: true,
          },
        },
      },
      {
        id: 137,
        translations: ["it", "ja"],
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,1&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/1",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,1",
        },
        streamStatus: "inactive",
        diarization: false,
        keepAudio: true,
        transcriberProfile: {
          config: {
            type: "microsoft",
            name: "DG SCIC Custom Model EN",
            description: "DG SCIC Custom Model EN",
            languages: [
              {
                candidate: "en-GB",
                endpoint: "f9e2c544-f6f7-4b74-89cc-67f8a722a358",
              },
            ],
            region: "westeurope",
            key: "4612cd17f7774661a481205178bb686a",
            availableTranslations: [
              "ar",
              "eu",
              "bs",
              "bg",
              "zh",
              "zhh",
              "cs",
              "da",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "gl",
              "de",
              "el",
              "hi",
              "hu",
              "id",
              "it",
              "ja",
              "ko",
              "lv",
              "lt",
              "mk",
              "nb",
              "pl",
              "pt",
              "ro",
              "ru",
              "sr",
              "sk",
              "sl",
              "es",
              "sv",
              "th",
              "tr",
              "uk",
              "vi",
              "cy",
            ],
            hasDiarization: true,
          },
        },
      },
    ],
  }

  const res = {
    id: "f4d59885-2c93-4a57-90c4-e977f163e87a",
    status: "active",
    name: "multi langue microsoft",
    startTime: "2025-01-14T12:59:17.140Z",
    endTime: null,
    scheduleOn: null,
    endOn: null,
    erroredOn: null,
    owner: "655f76185ebf391b4def21d0",
    organizationId: "6785238f0aee1be21684a9e1",
    visibility: "organization",
    autoStart: true,
    autoEnd: false,
    meta: null,
    createdAt: "2025-01-14T12:57:57.641Z",
    updatedAt: "2025-01-14T14:17:30.322Z",
    channels: [
      {
        id: 137,
        keepAudio: true,
        diarization: false,
        languages: ["en-GB"],
        translations: ["it", "ja"],
        name: "DG SCIC Custom Model EN",
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,1&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/1",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,1",
        },
        streamStatus: "inactive",
        transcriberId: null,
        closedCaptions: null,
        audioFile: "",
        bot: false,
        createdAt: "2025-01-14T12:57:57.649Z",
        updatedAt: "2025-01-14T12:57:57.656Z",
        transcriberProfileId: 2,
        index: 0,
        transcriberProfile: {
          config: {
            type: "microsoft",
            name: "DG SCIC Custom Model EN",
            description: "DG SCIC Custom Model EN",
            languages: [
              {
                candidate: "en-GB",
                endpoint: "f9e2c544-f6f7-4b74-89cc-67f8a722a358",
              },
            ],
            region: "westeurope",
            key: "4612cd17f7774661a481205178bb686a",
            availableTranslations: [
              "ar",
              "eu",
              "bs",
              "bg",
              "zh",
              "zhh",
              "cs",
              "da",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "gl",
              "de",
              "el",
              "hi",
              "hu",
              "id",
              "it",
              "ja",
              "ko",
              "lv",
              "lt",
              "mk",
              "nb",
              "pl",
              "pt",
              "ro",
              "ru",
              "sr",
              "sk",
              "sl",
              "es",
              "sv",
              "th",
              "tr",
              "uk",
              "vi",
              "cy",
            ],
            hasDiarization: true,
          },
        },
      },
      {
        id: 136,
        keepAudio: true,
        diarization: false,
        languages: ["fr-FR"],
        translations: ["en", "ar"],
        name: "DG SCIC Custom Model FR",
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,0&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/0",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,0",
        },
        streamStatus: "active",
        diarization: false,
        keepAudio: true,
        transcriberId: null,
        transcriberProfile: {
          config: {
            type: "microsoft",
            name: "DG SCIC Custom Model FR",
            description: "DG SCIC Custom Model FR",
            languages: [
              {
                candidate: "fr-FR",
                endpoint: "f8a073cb-27ea-45c4-80fb-c44a55297c95",
              },
            ],
            region: "westeurope",
            key: "4612cd17f7774661a481205178bb686a",
            availableTranslations: [
              "ar",
              "eu",
              "bs",
              "bg",
              "zh",
              "zhh",
              "cs",
              "da",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "gl",
              "de",
              "el",
              "hi",
              "hu",
              "id",
              "it",
              "ja",
              "ko",
              "lv",
              "lt",
              "mk",
              "nb",
              "pl",
              "pt",
              "ro",
              "ru",
              "sr",
              "sk",
              "sl",
              "es",
              "sv",
              "th",
              "tr",
              "uk",
              "vi",
              "cy",
            ],
            hasDiarization: true,
          },
        },
        closedCaptions: [
          {
            end: 30.07,
            lang: "fr-FR",
            text: "Comment peut-on atteindre ses fins ? Le mot fin FIN en français a 2 sens que tout paraît séparé mais qu'il faut peut être relier, rejoindre et où il y a aussi une forme de risque qu'il faut arriver à dépasser. Le terme fin, FIN toujours désigne en effet en français non seulement le terme atteint par une réalité dans son développement, par exemple à la fin de notre vie.",
            start: 4.39,
            astart: "2025-01-14T12:59:17.121Z",
            translations: {
              ar: "كيف يمكننا تحقيق غاياتنا؟ كلمة نهاية نهاية في الفرنسية لها معاني أن كل شيء يبدو منفصلا ولكن ربما يجب علينا الاتصال والانضمام وحيث يوجد أيضا شكل من أشكال المخاطر التي يجب أن نتمكن من التغلب عليها. يشير مصطلح النهاية ، FIN toujours ، بالفرنسية ليس فقط المصطلح الذي يصل إليه واقع في تطوره ، مثلا في نهاية حياتنا.",
              en: "How can we achieve our ends? The word end END in French has 2 meanings that everything seems separate but that we must perhaps connect, join and where there is also a form of risk that we must manage to overcome. The term end, FIN toujours, designates in French not only the term reached by a reality in its development, for example at the end of our life.",
            },
          },
          {
            end: 56.11,
            lang: "fr-FR",
            text: "La fin de vie qui est bornée en quelque sorte par l'expérience de la mort, mais il désigne aussi le terme ou le but fixé à une action dans la représentation humaine de l'action. Pour nous, esprit humain, l'action consiste en effet à se représenter un but que nous visons, un terme où l'action serait dite, achevée, accomplie. Il y a donc bien un lien entre les 2 sens du mot, mais dont nous sommes séparés par.",
            start: 30.39,
            astart: "2025-01-14T12:59:17.121Z",
            translations: {
              ar: "نهاية الحياة التي تقتصر بطريقة ما على تجربة الموت ، ولكنها تحدد أيضا المصطلح أو الهدف المحدد للفعل في التمثيل البشري للفعل. بالنسبة لنا، الروح البشرية، يتمثل الفعل في تمثيل هدف نسعى إليه لأنفسنا، مصطلح يقال فيه الفعل ويكتمل ويحقق. لذلك هناك رابط بين 2 من المعاني للكلمة ، ولكن نحن منفصلون عنهما.",
              en: "The end of life which is limited in a way by the experience of death, but it also designates the term or goal set for an action in the human representation of action. For us, the human spirit, action consists in representing to ourselves a goal that we aim at, a term at which the action would be said, completed, accomplished. So there is a link between the 2 meanings of the word, but from which we are separated by.",
            },
          },
        ],
        audioFile: "",
        bot: false,
        createdAt: "2025-01-14T12:57:57.644Z",
        updatedAt: "2025-01-14T14:17:30.313Z",
        transcriberProfileId: 1,
        index: 1,
      },
    ],
  }

  t.deepEqual(mergeSession(oldSession, newSession), res)
})

test("deep merge a session without channels with new values", (t) => {
  const oldSession = {
    id: "f4d59885-2c93-4a57-90c4-e977f163e87a",
    status: "ready",
    name: "multi langue microsoft",
    startTime: "2025-01-14T12:59:17.140Z",
    endTime: null,
    scheduleOn: null,
    endOn: null,
    erroredOn: null,
    owner: "655f76185ebf391b4def21d0",
    organizationId: "6785238f0aee1be21684a9e1",
    visibility: "organization",
    autoStart: true,
    autoEnd: false,
    meta: null,
    createdAt: "2025-01-14T12:57:57.641Z",
    updatedAt: "2025-01-14T14:17:30.322Z",
  }

  const newSession = {
    id: "f4d59885-2c93-4a57-90c4-e977f163e87a",
    status: "active",
    scheduleOn: null,
    endOn: null,
    autoStart: true,
    autoEnd: false,
    channels: [
      {
        id: 136,
        translations: ["en", "ar"],
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,0&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/0",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,0",
        },
        streamStatus: "active",
        diarization: false,
        keepAudio: true,
        transcriberProfile: {
          config: {
            type: "microsoft",
            name: "DG SCIC Custom Model FR",
            description: "DG SCIC Custom Model FR",
            languages: [
              {
                candidate: "fr-FR",
                endpoint: "f8a073cb-27ea-45c4-80fb-c44a55297c95",
              },
            ],
            region: "westeurope",
            key: "4612cd17f7774661a481205178bb686a",
            availableTranslations: [
              "ar",
              "eu",
              "bs",
              "bg",
              "zh",
              "zhh",
              "cs",
              "da",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "gl",
              "de",
              "el",
              "hi",
              "hu",
              "id",
              "it",
              "ja",
              "ko",
              "lv",
              "lt",
              "mk",
              "nb",
              "pl",
              "pt",
              "ro",
              "ru",
              "sr",
              "sk",
              "sl",
              "es",
              "sv",
              "th",
              "tr",
              "uk",
              "vi",
              "cy",
            ],
            hasDiarization: true,
          },
        },
      },
      {
        id: 137,
        translations: ["it", "ja"],
        streamEndpoints: {
          srt: "srt://127.0.0.1:8889?streamid=f4d59885-2c93-4a57-90c4-e977f163e87a,1&mode=caller",
          rtmp: "rtmp://127.0.0.1:1935/f4d59885-2c93-4a57-90c4-e977f163e87a/1",
          ws: "ws://127.0.0.1:8890/f4d59885-2c93-4a57-90c4-e977f163e87a,1",
        },
        streamStatus: "inactive",
        diarization: false,
        keepAudio: true,
        transcriberProfile: {
          config: {
            type: "microsoft",
            name: "DG SCIC Custom Model EN",
            description: "DG SCIC Custom Model EN",
            languages: [
              {
                candidate: "en-GB",
                endpoint: "f9e2c544-f6f7-4b74-89cc-67f8a722a358",
              },
            ],
            region: "westeurope",
            key: "4612cd17f7774661a481205178bb686a",
            availableTranslations: [
              "ar",
              "eu",
              "bs",
              "bg",
              "zh",
              "zhh",
              "cs",
              "da",
              "nl",
              "en",
              "et",
              "fi",
              "fr",
              "gl",
              "de",
              "el",
              "hi",
              "hu",
              "id",
              "it",
              "ja",
              "ko",
              "lv",
              "lt",
              "mk",
              "nb",
              "pl",
              "pt",
              "ro",
              "ru",
              "sr",
              "sk",
              "sl",
              "es",
              "sv",
              "th",
              "tr",
              "uk",
              "vi",
              "cy",
            ],
            hasDiarization: true,
          },
        },
      },
    ],
  }

  const res = {
    id: "f4d59885-2c93-4a57-90c4-e977f163e87a",
    status: "active",
    name: "multi langue microsoft",
    startTime: "2025-01-14T12:59:17.140Z",
    endTime: null,
    scheduleOn: null,
    endOn: null,
    erroredOn: null,
    owner: "655f76185ebf391b4def21d0",
    organizationId: "6785238f0aee1be21684a9e1",
    visibility: "organization",
    autoStart: true,
    autoEnd: false,
    meta: null,
    createdAt: "2025-01-14T12:57:57.641Z",
    updatedAt: "2025-01-14T14:17:30.322Z",
    channels: [],
  }

  t.deepEqual(mergeSession(oldSession, newSession), res)
})
