version: '3.5'

services:
  studio-mongo:
    container_name: studio-mongo
    image: mongo:5.0
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    expose:
      - "27017"
    networks:
      - linto-net

networks:
  linto-net:
    external: true
