version: '3.5'

services:
  studio-mongo:
    container_name: studio-mongo
    image: mongo:latest
    volumes:
      - ./docker-optional/mongo-database/:/data/db
    ports:
      - 27017:27017
    expose:
      - "27017"
