import type { Component } from "vue"
import {
  ArrowDown,
  Bold,
  Check,
  ChevronDown,
  ClipboardList,
  ClipboardType,
  Code,
  Code2,
  Copy,
  Download,
  FileText,
  Heading1,
  Heading2,
  Heading3,
  Italic,
  List,
  ListOrdered,
  Loader2,
  Table as TableIcon,
  MessageCircle,
  MoreVertical,
  Pause,
  Play,
  Quote,
  Redo2,
  RefreshCw,
  Settings,
  SkipBack,
  SkipForward,
  Sparkles,
  Undo2,
  UserPlus,
  Users,
  Volume2,
  VolumeX,
  X,
} from "lucide-vue-next"

export const iconMap: Record<string, Component> = {
  "arrow-down": ArrowDown,
  bold: Bold,
  check: Check,
  "chevron-down": ChevronDown,
  "clipboard-list": ClipboardList,
  "clipboard-type": ClipboardType,
  code: Code,
  "code-block": Code2,
  copy: Copy,
  download: Download,
  "heading-1": Heading1,
  "heading-2": Heading2,
  "heading-3": Heading3,
  italic: Italic,
  list: List,
  "list-ordered": ListOrdered,
  pause: Pause,
  play: Play,
  quote: Quote,
  redo: Redo2,
  table: TableIcon,
  settings: Settings,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  undo: Undo2,
  users: Users,
  volume: Volume2,
  "volume-mute": VolumeX,
  x: X,
  "circle-notch": Loader2,
  spinner: Loader2,
  "more-vertical": MoreVertical,
  "user-plus": UserPlus,
  "file-text": FileText,
  "message-circle": MessageCircle,
  "refresh-cw": RefreshCw,
  sparkles: Sparkles,
}

export function resolveIcon(name?: string): Component | undefined {
  if (!name) return undefined
  return iconMap[name]
}

export const ICON_SIZES: Record<"sm" | "md" | "lg", number> = {
  sm: 16,
  md: 20,
  lg: 24,
}
