// Service worker of the mobile app (Workbox generateSW via vite-plugin-pwa).
// Scope is /m/ only: the classic app on / is never controlled or cached.
// The manifest and icons are static files in public/, so the plugin does not
// generate a manifest. config.js is regenerated by docker-entrypoint.sh at
// container start: never precached, network first.
const ONE_YEAR_SECONDS = 365 * 24 * 60 * 60
const ONE_DAY_SECONDS = 24 * 60 * 60

export const mobileServiceWorkerOptions = {
  strategies: "generateSW",
  registerType: "autoUpdate",
  injectRegister: false,
  manifest: false,
  filename: "sw-mobile.js",
  scope: "/m/",
  base: "/",
  includeAssets: [],
  workbox: {
    // Only the mobile shell is precached; hashed chunks are cached on use.
    globPatterns: ["mobile.html", "manifest.webmanifest", "img/pwa/*.png"],
    navigateFallback: "/mobile.html",
    navigateFallbackAllowlist: [/^\/m(\/|$)/],
    skipWaiting: true,
    clientsClaim: true,
    cleanupOutdatedCaches: true,
    runtimeCaching: [
      {
        urlPattern: /\/config\.js$/,
        handler: "NetworkFirst",
        options: { cacheName: "mobile-config", networkTimeoutSeconds: 3 },
      },
      {
        urlPattern: /\/assets\/.*\.(js|css)$/,
        handler: "CacheFirst",
        options: {
          cacheName: "mobile-assets",
          expiration: { maxEntries: 200, maxAgeSeconds: ONE_YEAR_SECONDS },
        },
      },
      {
        urlPattern: /\/(fonts|img)\/.*\.(css|woff2?|ttf|svg|png)$/,
        handler: "CacheFirst",
        options: {
          cacheName: "mobile-static",
          expiration: { maxEntries: 100, maxAgeSeconds: ONE_YEAR_SECONDS },
        },
      },
      {
        urlPattern: /\/mobile\.html$/,
        handler: "NetworkFirst",
        options: {
          cacheName: "mobile-shell",
          networkTimeoutSeconds: 3,
          expiration: { maxAgeSeconds: ONE_DAY_SECONDS },
        },
      },
    ],
  },
}
