openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Conversation manager API client'
  description: 'Blah blah'
  termsOfService: https://doc.linto.ai/#/?id=gnu-affero-general-public-licence-v3
  contact:
    name: LINAGORA
    url: http://linto.ai
    email: contact@linto.ai
# paths: {}
host: localhost:8000
basePath: /api
schemes:
 - https
paths:
  /:
    get:
      security:
        - cookieAuth: []
      description: sdfasdaf
      responses: 
        '200':
          description: OK
        '401':
          description: Not authenticated
        '404':
          description: Page not found 

  /login:
    post:
      summary: Logs in and returns the authentication  cookie
      requestBody:
        required: true
        description: A JSON object containing the login and password.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      # security: []    # no authentication
      responses:
        '200':
          description: 
            Successfully authenticated.
            The session ID is returned in a cookie named `JSESSIONID`. You need to include this cookie in subsequent requests.
          headers: 
            Set-Cookie:
              schema: 
                type: string
                example: JSESSIONID=abcde12345; Path=/; HttpOnly


components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string 
        password:
          type: string
security:
  - cookieAuth: []
