export default {
  VUE_APP_NAME: "LinTO Studio",
  VUE_APP_LOGO: null,
  VUE_APP_CONVO_API: "http://127.0.0.1:8001/api",
  VUE_APP_CONVO_AUTH: "http://127.0.0.1:8001/auth",
  VUE_APP_SESSION_WS: "http://127.0.0.1:8001",
  VUE_APP_ENABLE_SESSION: "false",
  VUE_APP_SHOW_LOGIN_FOOTER: "false",
  VUE_APP_WEBSOCKET_TRANSPORTS: "websocket",
  VUE_APP_DEFAULT_METADATA: "",
  VUE_APP_ENABLE_WATERMARK: "false",
  VUE_APP_WATERMARK_FREQUENCY: "600",
  VUE_APP_WATERMARK_DURATION: "10",
  VUE_APP_SHOW_BETA_LIVE_TRANSCRIPTION: "false",
  VUE_APP_WATERMARK_CONTENT:
    "Transcription by LinTO.ai $linto Open Source AI by $linagora",
  VUE_APP_MODE: "basic",
  VUE_APP_ENABLE_SECURITY_LEVEL: "false",
}
