const TRANSCRIBER_PROFILES_TEMPLATES = {
  linto: {
    config: {
      type: "linto",
      name: "linto asr name",
      description: "asr description",
      languages: [
        {
          candidate: "fr-fr",
          endpoint: "ws://127.0.0.1:8080/streaming",
        },
      ],
      availableTranslations: [],
      hasDiarization: false,
    },
    organizationId: null,
    quickMeeting: true,
  },
  microsoft: {
    config: {
      type: "microsoft",
      name: "microsoft asr name",
      description: "asr description",
      languages: [
        {
          candidate: "en-GB",
          endpoint: "f9e2c544-f6f7-4b74-89cc-67f8a722a358",
        },
        {
          candidate: "fr-FR",
          endpoint: "f8a073cb-27ea-45c4-80fb-c44a55297c95",
        },
      ],
      region: "westeurope",
      key: "your_key",
      availableTranslations: [
        "ar",
        "eu",
        "bs",
        "bg",
        "zh",
        "zhh",
        "cs",
        "da",
        "nl",
        "en",
        "et",
        "fi",
        "fr",
        "gl",
        "de",
        "el",
        "hi",
        "hu",
        "id",
        "it",
        "ja",
        "ko",
        "lv",
        "lt",
        "mk",
        "nb",
        "pl",
        "pt",
        "ro",
        "ru",
        "sr",
        "sk",
        "sl",
        "es",
        "sv",
        "th",
        "tr",
        "uk",
        "vi",
        "cy",
      ],
      hasDiarization: true,
    },
    organizationId: null,
    quickMeeting: true,
  },
}

export default TRANSCRIBER_PROFILES_TEMPLATES
